//! Criterion benchmarks for the JSONL event encoding pipeline.
//!
//! Measures throughput of each encoding primitive (`write_u64`, `write_oid_hex`,
//! `write_json_str`, `write_json_bytes`, `write_f64`) and end-to-end event
//! encoding (`encode_finding`, `encode_commit_meta`, batch encoding, and
//! `JsonlEventSink` emission).
//!
//! ## Determinism
//!
//! All data is generated by a local [`XorShift64`] PRNG seeded with fixed
//! constants — no `rand` dependency, fully reproducible across runs.

use criterion::{black_box, criterion_group, criterion_main, BenchmarkId, Criterion, Throughput};
use scanner_rs::git_scan::identity_intern::CommitIdentityIds;
use scanner_rs::git_scan::object_id::OidBytes;
use scanner_rs::unified::events::{
    encode_commit_meta, encode_finding, CommitMetaEvent, EventEncoder, EventSink, FindingEvent,
    JsonlEncoder, JsonlEventSink, ScanEvent,
};
use scanner_rs::unified::SourceKind;
use std::io;

// ============================================================================
// Deterministic PRNG (no `rand` dependency)
// ============================================================================

struct XorShift64 {
    state: u64,
}

impl XorShift64 {
    fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    fn next_u64(&mut self) -> u64 {
        let mut x = self.state;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.state = x;
        x
    }

    fn fill_bytes(&mut self, out: &mut [u8]) {
        let mut i = 0usize;
        while i < out.len() {
            let mut v = self.next_u64();
            let take = (out.len() - i).min(8);
            for j in 0..take {
                out[i + j] = (v & 0xff) as u8;
                v >>= 8;
            }
            i += take;
        }
    }
}

// ============================================================================
// Data generators
// ============================================================================

/// Generate a clean ASCII string of length `n` (printable, no escapes needed).
fn make_clean_ascii(n: usize) -> String {
    let mut rng = XorShift64::new(0xCAFE_BABE_0000 + n as u64);
    let mut s = String::with_capacity(n);
    for _ in 0..n {
        // ASCII printable range [0x21..0x7e] excluding '"' (0x22) and '\\' (0x5c)
        let mut b = (rng.next_u64() % 93 + 0x21) as u8;
        if b == b'"' {
            b = b'a';
        }
        if b == b'\\' {
            b = b'b';
        }
        s.push(b as char);
    }
    s
}

/// Generate a string of length `n` with an escape-worthy char every 16 bytes.
fn make_ascii_with_escapes(n: usize) -> String {
    let mut rng = XorShift64::new(0xDEAD_BEEF_0000 + n as u64);
    let mut s = String::with_capacity(n);
    for i in 0..n {
        if i % 16 == 0 {
            s.push('"'); // needs escaping
        } else {
            let mut b = (rng.next_u64() % 93 + 0x21) as u8;
            if b == b'"' {
                b = b'a';
            }
            if b == b'\\' {
                b = b'b';
            }
            s.push(b as char);
        }
    }
    s
}

/// Generate clean ASCII bytes of length `n`.
fn make_clean_bytes(n: usize) -> Vec<u8> {
    make_clean_ascii(n).into_bytes()
}

/// Generate bytes with a 0xff at position 10 (forces scalar fallback).
fn make_bytes_with_high(n: usize) -> Vec<u8> {
    let mut v = make_clean_bytes(n);
    if v.len() > 10 {
        v[10] = 0xff;
    }
    v
}

fn make_sha1_oid() -> OidBytes {
    let mut bytes = [0u8; 20];
    let mut rng = XorShift64::new(0x51A1_0000);
    rng.fill_bytes(&mut bytes);
    OidBytes::sha1(bytes)
}

fn make_sha256_oid() -> OidBytes {
    let mut bytes = [0u8; 32];
    let mut rng = XorShift64::new(0x256_0000);
    rng.fill_bytes(&mut bytes);
    OidBytes::sha256(bytes)
}

fn make_fs_finding() -> FindingEvent<'static> {
    FindingEvent {
        source: SourceKind::Fs,
        object_path: b"src/config/database.yaml",
        start: 1024,
        end: 1080,
        rule_id: 7,
        rule_name: "aws-access-key",
        commit_id: None,
        change_kind: None,
    }
}

fn make_git_finding() -> FindingEvent<'static> {
    FindingEvent {
        source: SourceKind::Git,
        object_path: b"services/auth/credentials.env",
        start: 42,
        end: 82,
        rule_id: 3,
        rule_name: "generic-secret",
        commit_id: Some(12345),
        change_kind: Some("add"),
    }
}

fn make_commit_meta_no_identity() -> CommitMetaEvent {
    CommitMetaEvent {
        commit_id: 42,
        commit_oid: make_sha1_oid(),
        timestamp: 1_700_000_000,
        identity: None,
    }
}

fn make_commit_meta_with_identity() -> CommitMetaEvent {
    CommitMetaEvent {
        commit_id: 42,
        commit_oid: make_sha1_oid(),
        timestamp: 1_700_000_000,
        identity: Some(CommitIdentityIds {
            author_name: 0,
            author_email: 1,
            committer_name: 2,
            committer_email: 3,
        }),
    }
}

// ============================================================================
// Primitive microbenchmarks
// ============================================================================

fn bench_write_u64(c: &mut Criterion) {
    use scanner_rs::unified::json_write::write_u64;
    let mut group = c.benchmark_group("write_u64");

    for &(label, val) in &[
        ("small_42", 42u64),
        ("medium_1_7B", 1_700_000_000),
        ("large_u64_max", u64::MAX),
    ] {
        group.throughput(Throughput::Elements(1));
        group.bench_with_input(BenchmarkId::new("value", label), &val, |b, &n| {
            let mut buf = Vec::with_capacity(20);
            b.iter(|| {
                buf.clear();
                write_u64(black_box(n), &mut buf);
                black_box(&buf);
            });
        });
    }
    group.finish();
}

fn bench_write_oid_hex(c: &mut Criterion) {
    use scanner_rs::unified::json_write::write_oid_hex;
    let mut group = c.benchmark_group("write_oid_hex");

    let sha1 = make_sha1_oid();
    let sha256 = make_sha256_oid();

    group.throughput(Throughput::Bytes(40));
    group.bench_function("sha1_20B", |b| {
        let mut buf = Vec::with_capacity(64);
        b.iter(|| {
            buf.clear();
            write_oid_hex(black_box(&sha1), &mut buf);
            black_box(&buf);
        });
    });

    group.throughput(Throughput::Bytes(64));
    group.bench_function("sha256_32B", |b| {
        let mut buf = Vec::with_capacity(64);
        b.iter(|| {
            buf.clear();
            write_oid_hex(black_box(&sha256), &mut buf);
            black_box(&buf);
        });
    });

    group.finish();
}

fn bench_write_json_str(c: &mut Criterion) {
    use scanner_rs::unified::json_write::write_json_str;
    let mut group = c.benchmark_group("write_json_str");

    for &size in &[32, 128, 512] {
        let clean = make_clean_ascii(size);
        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::new("clean_ascii", size), &clean, |b, s| {
            let mut buf = Vec::with_capacity(size + 64);
            b.iter(|| {
                buf.clear();
                write_json_str(black_box(s), &mut buf);
                black_box(&buf);
            });
        });
    }

    for &size in &[32, 128, 512] {
        let escaped = make_ascii_with_escapes(size);
        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::new("with_escapes", size), &escaped, |b, s| {
            let mut buf = Vec::with_capacity(size * 2);
            b.iter(|| {
                buf.clear();
                write_json_str(black_box(s), &mut buf);
                black_box(&buf);
            });
        });
    }

    group.finish();
}

fn bench_write_json_bytes(c: &mut Criterion) {
    use scanner_rs::unified::json_write::write_json_bytes;
    let mut group = c.benchmark_group("write_json_bytes");

    let clean = make_clean_bytes(128);
    group.throughput(Throughput::Bytes(128));
    group.bench_function("clean_ascii_128B", |b| {
        let mut buf = Vec::with_capacity(256);
        b.iter(|| {
            buf.clear();
            write_json_bytes(black_box(&clean), &mut buf);
            black_box(&buf);
        });
    });

    let with_high = make_bytes_with_high(128);
    group.throughput(Throughput::Bytes(128));
    group.bench_function("with_0xff_128B", |b| {
        let mut buf = Vec::with_capacity(256);
        b.iter(|| {
            buf.clear();
            write_json_bytes(black_box(&with_high), &mut buf);
            black_box(&buf);
        });
    });

    group.finish();
}

fn bench_write_f64(c: &mut Criterion) {
    use scanner_rs::unified::json_write::write_f64;
    let mut group = c.benchmark_group("write_f64");
    group.throughput(Throughput::Elements(1));
    group.bench_function("81.23", |b| {
        let mut buf = Vec::with_capacity(32);
        b.iter(|| {
            buf.clear();
            write_f64(black_box(81.23), &mut buf);
            black_box(&buf);
        });
    });
    group.finish();
}

// ============================================================================
// Encoder-level benchmarks
// ============================================================================

fn bench_encode_finding(c: &mut Criterion) {
    let mut group = c.benchmark_group("encode_finding");
    group.throughput(Throughput::Elements(1));

    let fs_finding = make_fs_finding();
    group.bench_function("fs_finding", |b| {
        let mut buf = Vec::with_capacity(256);
        b.iter(|| {
            buf.clear();
            encode_finding(black_box(&fs_finding), &mut buf);
            black_box(&buf);
        });
    });

    let git_finding = make_git_finding();
    group.bench_function("git_finding", |b| {
        let mut buf = Vec::with_capacity(256);
        b.iter(|| {
            buf.clear();
            encode_finding(black_box(&git_finding), &mut buf);
            black_box(&buf);
        });
    });

    group.finish();
}

fn bench_encode_commit_meta(c: &mut Criterion) {
    let mut group = c.benchmark_group("encode_commit_meta");
    group.throughput(Throughput::Elements(1));

    let no_id = make_commit_meta_no_identity();
    group.bench_function("no_identity", |b| {
        let mut buf = Vec::with_capacity(256);
        b.iter(|| {
            buf.clear();
            encode_commit_meta(black_box(&no_id), &mut buf);
            black_box(&buf);
        });
    });

    let with_id = make_commit_meta_with_identity();
    group.bench_function("with_identity", |b| {
        let mut buf = Vec::with_capacity(256);
        b.iter(|| {
            buf.clear();
            encode_commit_meta(black_box(&with_id), &mut buf);
            black_box(&buf);
        });
    });

    group.finish();
}

fn bench_encode_batch(c: &mut Criterion) {
    let mut group = c.benchmark_group("encode_batch");
    let encoder = JsonlEncoder::new();

    group.throughput(Throughput::Elements(1000));
    group.bench_function("1000_findings", |b| {
        let mut buf = Vec::with_capacity(256 * 1000);
        let findings: Vec<FindingEvent<'static>> = (0..1000)
            .map(|i| {
                if i % 2 == 0 {
                    make_fs_finding()
                } else {
                    make_git_finding()
                }
            })
            .collect();
        b.iter(|| {
            buf.clear();
            for f in &findings {
                encoder.encode(
                    &ScanEvent::Finding(FindingEvent {
                        source: f.source,
                        object_path: f.object_path,
                        start: f.start,
                        end: f.end,
                        rule_id: f.rule_id,
                        rule_name: f.rule_name,
                        commit_id: f.commit_id,
                        change_kind: f.change_kind,
                    }),
                    &mut buf,
                );
            }
            black_box(&buf);
        });
    });

    group.finish();
}

/// Sink benchmark: emit 1000 findings into /dev/null.
fn bench_sink_emit(c: &mut Criterion) {
    let mut group = c.benchmark_group("sink_emit");
    group.throughput(Throughput::Elements(1000));

    group.bench_function("1000_findings_dev_null", |b| {
        let sink = JsonlEventSink::new(io::sink());
        let findings: Vec<FindingEvent<'static>> = (0..1000)
            .map(|i| {
                if i % 2 == 0 {
                    make_fs_finding()
                } else {
                    make_git_finding()
                }
            })
            .collect();
        b.iter(|| {
            for f in &findings {
                sink.emit(ScanEvent::Finding(FindingEvent {
                    source: f.source,
                    object_path: f.object_path,
                    start: f.start,
                    end: f.end,
                    rule_id: f.rule_id,
                    rule_name: f.rule_name,
                    commit_id: f.commit_id,
                    change_kind: f.change_kind,
                }));
            }
        });
    });

    group.finish();
}

criterion_group!(
    primitives,
    bench_write_u64,
    bench_write_oid_hex,
    bench_write_json_str,
    bench_write_json_bytes,
    bench_write_f64,
);
criterion_group!(
    encoding,
    bench_encode_finding,
    bench_encode_commit_meta,
    bench_encode_batch,
    bench_sink_emit,
);
criterion_main!(primitives, encoding);
