//! Criterion benchmarks for the JSONL event encoding pipeline.
//!
//! These benchmarks quantify the cost of serializing scan results into JSONL
//! lines — the hot path for every finding and commit-meta record emitted
//! during a scan. They exist to catch regressions in the hand-rolled
//! JSON-writing primitives (which use SIMD fast paths on aarch64/x86_64)
//! and to validate that end-to-end event encoding stays below ~100 ns per
//! event on typical hardware.
//!
//! ## What is measured
//!
//! | Group | Functions | Key metric |
//! |---|---|---|
//! | `primitives` | `write_u64`, `write_oid_hex`, `write_json_str`, `write_json_bytes`, `write_f64` | Bytes/sec throughput |
//! | `encoding` | `encode_finding`, `encode_commit_meta`, batch encode, `JsonlEventSink::emit` | Events/sec throughput |
//!
//! ## Running
//!
//! ```sh
//! cargo bench --bench event_encoding           # full suite
//! cargo bench --bench event_encoding -- write_  # only primitives
//! cargo bench --bench event_encoding -- encode_ # only encoder-level
//! ```
//!
//! ## Determinism
//!
//! All data is generated by a local [`XorShift64`] PRNG seeded with fixed
//! constants — no `rand` dependency, fully reproducible across runs.

use criterion::{black_box, criterion_group, criterion_main, BenchmarkId, Criterion, Throughput};
use scanner_rs::git_scan::identity_intern::CommitIdentityIds;
use scanner_rs::git_scan::object_id::OidBytes;
use scanner_rs::unified::events::{
    encode_commit_meta, encode_finding, CommitMetaEvent, EventEncoder, EventSink, FindingEvent,
    JsonlEncoder, JsonlEventSink, ScanEvent,
};
use scanner_rs::unified::SourceKind;
use std::io;

// ============================================================================
// Deterministic PRNG (no `rand` dependency)
// ============================================================================

/// Minimal xorshift64 PRNG for generating deterministic benchmark inputs.
///
/// We avoid pulling in `rand` just for benchmarks — a full-featured RNG
/// isn't needed since the only requirement is repeatability across runs
/// (identical seeds → identical byte sequences). The quality of randomness
/// is irrelevant; we just need diverse-looking data that exercises the
/// encoder's code paths consistently.
struct XorShift64 {
    state: u64,
}

impl XorShift64 {
    fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    fn next_u64(&mut self) -> u64 {
        let mut x = self.state;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.state = x;
        x
    }

    fn fill_bytes(&mut self, out: &mut [u8]) {
        let mut i = 0usize;
        while i < out.len() {
            let mut v = self.next_u64();
            let take = (out.len() - i).min(8);
            for j in 0..take {
                out[i + j] = (v & 0xff) as u8;
                v >>= 8;
            }
            i += take;
        }
    }
}

// ============================================================================
// Data generators
// ============================================================================

/// Generate a clean ASCII string of length `n` (printable, no escapes needed).
///
/// Excludes `"` and `\\` so the string passes through `write_json_str` without
/// triggering any escape logic — this isolates the SIMD bulk-copy fast path
/// and gives a ceiling measurement for string-writing throughput.
fn make_clean_ascii(n: usize) -> String {
    let mut rng = XorShift64::new(0xCAFE_BABE_0000 + n as u64);
    let mut s = String::with_capacity(n);
    for _ in 0..n {
        // ASCII printable range [0x21..0x7e] excluding '"' (0x22) and '\\' (0x5c)
        let mut b = (rng.next_u64() % 93 + 0x21) as u8;
        if b == b'"' {
            b = b'a';
        }
        if b == b'\\' {
            b = b'b';
        }
        s.push(b as char);
    }
    s
}

/// Generate a string of length `n` with a `"` every 16 bytes that requires escaping.
///
/// The 1-in-16 ratio is deliberately chosen to model realistic path/rule-name
/// strings that occasionally contain characters needing JSON escaping. It forces
/// the SIMD scanner to find a hit roughly once per 16-byte NEON/SSE register
/// load, exercising the SIMD→scalar fallback transition on every chunk.
fn make_ascii_with_escapes(n: usize) -> String {
    let mut rng = XorShift64::new(0xDEAD_BEEF_0000 + n as u64);
    let mut s = String::with_capacity(n);
    for i in 0..n {
        if i % 16 == 0 {
            s.push('"'); // needs escaping
        } else {
            let mut b = (rng.next_u64() % 93 + 0x21) as u8;
            if b == b'"' {
                b = b'a';
            }
            if b == b'\\' {
                b = b'b';
            }
            s.push(b as char);
        }
    }
    s
}

/// Generate a string of length `n` with escapes placed sparsely (not every chunk).
///
/// Places `"` characters at positions 50, 150, and 350 (if within range).
/// This models realistic file paths where most of the string is clean ASCII
/// but occasional characters need escaping. Unlike [`make_ascii_with_escapes`]
/// which bails SIMD on every chunk, this exercises the SIMD resume-after-escape
/// path where most chunks pass through the fast path.
fn make_sparse_escapes(n: usize) -> String {
    let mut rng = XorShift64::new(0xFACE_CAFE_0000 + n as u64);
    let mut s = String::with_capacity(n);
    let escape_positions = [50, 150, 350];
    for i in 0..n {
        if escape_positions.contains(&i) {
            s.push('"');
        } else {
            let mut b = (rng.next_u64() % 93 + 0x21) as u8;
            if b == b'"' {
                b = b'a';
            }
            if b == b'\\' {
                b = b'b';
            }
            s.push(b as char);
        }
    }
    s
}

/// Generate clean ASCII bytes of length `n`.
fn make_clean_bytes(n: usize) -> Vec<u8> {
    make_clean_ascii(n).into_bytes()
}

/// Generate bytes with a `0xFF` at position 10 (forces scalar fallback).
///
/// `write_json_bytes` must hex-escape any byte outside the printable ASCII
/// range. Placing a single high byte early exercises the transition from the
/// SIMD all-ASCII fast path into the scalar escape handler, which is the
/// most expensive per-byte code path in the byte writer.
fn make_bytes_with_high(n: usize) -> Vec<u8> {
    let mut v = make_clean_bytes(n);
    if v.len() > 10 {
        v[10] = 0xff;
    }
    v
}

/// Fixed SHA-1 OID (20 bytes → 40 hex chars) for `write_oid_hex` benchmarks.
fn make_sha1_oid() -> OidBytes {
    let mut bytes = [0u8; 20];
    let mut rng = XorShift64::new(0x51A1_0000);
    rng.fill_bytes(&mut bytes);
    OidBytes::sha1(bytes)
}

/// Fixed SHA-256 OID (32 bytes → 64 hex chars) for `write_oid_hex` benchmarks.
fn make_sha256_oid() -> OidBytes {
    let mut bytes = [0u8; 32];
    let mut rng = XorShift64::new(0x256_0000);
    rng.fill_bytes(&mut bytes);
    OidBytes::sha256(bytes)
}

/// Filesystem-sourced finding — no `commit_id` or `change_kind` fields.
///
/// Models the simpler code path where optional Git-specific fields are `None`,
/// producing a shorter JSON line. Paired with [`make_git_finding`] to measure
/// the cost difference between the two variants.
fn make_fs_finding() -> FindingEvent<'static> {
    FindingEvent {
        source: SourceKind::Fs,
        object_path: b"src/config/database.yaml",
        start: 1024,
        end: 1080,
        rule_id: 7,
        rule_name: "aws-access-key",
        commit_id: None,
        change_kind: None,
    }
}

/// Git-sourced finding — includes `commit_id` and `change_kind` fields.
///
/// Exercises the longer encoding path with two extra JSON key-value pairs.
/// The `commit_id` adds a `write_u64` call and `change_kind` adds a
/// `write_json_str` call, so this variant is the ceiling cost per finding.
fn make_git_finding() -> FindingEvent<'static> {
    FindingEvent {
        source: SourceKind::Git,
        object_path: b"services/auth/credentials.env",
        start: 42,
        end: 82,
        rule_id: 3,
        rule_name: "generic-secret",
        commit_id: Some(12345),
        change_kind: Some("add"),
    }
}

/// Commit metadata without identity (author/committer) — shortest variant.
fn make_commit_meta_no_identity() -> CommitMetaEvent {
    CommitMetaEvent {
        commit_id: 42,
        commit_oid: make_sha1_oid(),
        timestamp: 1_700_000_000,
        identity: None,
    }
}

/// Commit metadata with all four identity IDs — longest variant.
///
/// The identity fields add four `write_u64` calls, which is the overhead
/// we want to track relative to the no-identity baseline.
fn make_commit_meta_with_identity() -> CommitMetaEvent {
    CommitMetaEvent {
        commit_id: 42,
        commit_oid: make_sha1_oid(),
        timestamp: 1_700_000_000,
        identity: Some(CommitIdentityIds {
            author_name: 0,
            author_email: 1,
            committer_name: 2,
            committer_email: 3,
        }),
    }
}

// ============================================================================
// Primitive microbenchmarks
// ============================================================================

/// Measure `write_u64` across three magnitude bands.
///
/// The two-digits-at-a-time lookup table means cost scales with digit count,
/// not with the numeric value itself. The three cases (1-digit, 10-digit,
/// 20-digit) confirm that per-digit cost is constant.
fn bench_write_u64(c: &mut Criterion) {
    use scanner_rs::unified::json_write::write_u64;
    let mut group = c.benchmark_group("write_u64");

    for &(label, val) in &[
        ("small_42", 42u64),
        ("medium_1_7B", 1_700_000_000),
        ("large_u64_max", u64::MAX),
    ] {
        group.throughput(Throughput::Elements(1));
        group.bench_with_input(BenchmarkId::new("value", label), &val, |b, &n| {
            let mut buf = Vec::with_capacity(20);
            b.iter(|| {
                buf.clear();
                write_u64(black_box(n), &mut buf);
                black_box(&buf);
            });
        });
    }
    group.finish();
}

/// Measure `write_oid_hex` for SHA-1 (40 hex chars) and SHA-256 (64 hex chars).
///
/// Both use the same 256-entry lookup table with bulk pointer writes. The
/// SHA-256 case should be ~1.6× the SHA-1 cost, confirming linear scaling
/// with no per-call overhead domination.
fn bench_write_oid_hex(c: &mut Criterion) {
    use scanner_rs::unified::json_write::write_oid_hex;
    let mut group = c.benchmark_group("write_oid_hex");

    let sha1 = make_sha1_oid();
    let sha256 = make_sha256_oid();

    group.throughput(Throughput::Bytes(40));
    group.bench_function("sha1_20B", |b| {
        let mut buf = Vec::with_capacity(64);
        b.iter(|| {
            buf.clear();
            write_oid_hex(black_box(&sha1), &mut buf);
            black_box(&buf);
        });
    });

    group.throughput(Throughput::Bytes(64));
    group.bench_function("sha256_32B", |b| {
        let mut buf = Vec::with_capacity(64);
        b.iter(|| {
            buf.clear();
            write_oid_hex(black_box(&sha256), &mut buf);
            black_box(&buf);
        });
    });

    group.finish();
}

/// Measure `write_json_str` across string lengths (32, 128, 512 bytes) and
/// two content profiles: clean ASCII (SIMD-only) and escape-heavy (1-in-16).
///
/// The clean vs. escaped comparison quantifies the cost of SIMD→scalar
/// fallbacks. On aarch64 with NEON, clean ASCII should approach memcpy speed;
/// the escaped variant should be measurably slower but still sub-linear in
/// escape count thanks to the 16-byte bulk scan.
fn bench_write_json_str(c: &mut Criterion) {
    use scanner_rs::unified::json_write::write_json_str;
    let mut group = c.benchmark_group("write_json_str");

    // Sub-16-byte strings: always take the scalar path (below SIMD threshold).
    // Rule names like "aws-access-key" (14 chars) fall in this range.
    for &size in &[4, 8, 14] {
        let clean = make_clean_ascii(size);
        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::new("scalar_short", size), &clean, |b, s| {
            let mut buf = Vec::with_capacity(size + 16);
            b.iter(|| {
                buf.clear();
                write_json_str(black_box(s), &mut buf);
                black_box(&buf);
            });
        });
    }

    for &size in &[32, 128, 512] {
        let clean = make_clean_ascii(size);
        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::new("clean_ascii", size), &clean, |b, s| {
            let mut buf = Vec::with_capacity(size + 64);
            b.iter(|| {
                buf.clear();
                write_json_str(black_box(s), &mut buf);
                black_box(&buf);
            });
        });
    }

    for &size in &[32, 128, 512] {
        let escaped = make_ascii_with_escapes(size);
        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::new("with_escapes", size), &escaped, |b, s| {
            let mut buf = Vec::with_capacity(size * 2);
            b.iter(|| {
                buf.clear();
                write_json_str(black_box(s), &mut buf);
                black_box(&buf);
            });
        });
    }

    // Sparse escapes: only a few escapes in a long string — exercises SIMD
    // resume-after-escape (most chunks pass all-safe check).
    let sparse = make_sparse_escapes(512);
    group.throughput(Throughput::Bytes(512));
    group.bench_with_input(BenchmarkId::new("sparse_escapes", 512), &sparse, |b, s| {
        let mut buf = Vec::with_capacity(512 + 64);
        b.iter(|| {
            buf.clear();
            write_json_str(black_box(s), &mut buf);
            black_box(&buf);
        });
    });

    group.finish();
}

/// Measure `write_json_bytes` for clean ASCII vs. a buffer containing `0xFF`.
///
/// Git object paths are raw bytes (not guaranteed UTF-8), so `write_json_bytes`
/// must handle high bytes via Unicode escape (`\\u00XX`). The `with_0xff` variant
/// confirms the scalar fallback cost is bounded.
fn bench_write_json_bytes(c: &mut Criterion) {
    use scanner_rs::unified::json_write::write_json_bytes;
    let mut group = c.benchmark_group("write_json_bytes");

    let clean = make_clean_bytes(128);
    group.throughput(Throughput::Bytes(128));
    group.bench_function("clean_ascii_128B", |b| {
        let mut buf = Vec::with_capacity(256);
        b.iter(|| {
            buf.clear();
            write_json_bytes(black_box(&clean), &mut buf);
            black_box(&buf);
        });
    });

    let with_high = make_bytes_with_high(128);
    group.throughput(Throughput::Bytes(128));
    group.bench_function("with_0xff_128B", |b| {
        let mut buf = Vec::with_capacity(256);
        b.iter(|| {
            buf.clear();
            write_json_bytes(black_box(&with_high), &mut buf);
            black_box(&buf);
        });
    });

    group.finish();
}

/// Measure `write_f64` with a representative two-decimal-place value.
///
/// `write_f64` uses a hand-rolled fixed-precision formatter (integer part via
/// `write_u64`, fractional part via two-digit lookup) — no `ryu` dependency.
/// This benchmark exists mainly as a regression guard — f64 fields are rare
/// in scan events today but the primitive is shared infrastructure.
fn bench_write_f64(c: &mut Criterion) {
    use scanner_rs::unified::json_write::write_f64;
    let mut group = c.benchmark_group("write_f64");
    group.throughput(Throughput::Elements(1));
    group.bench_function("81.23", |b| {
        let mut buf = Vec::with_capacity(32);
        b.iter(|| {
            buf.clear();
            write_f64(black_box(81.23), &mut buf);
            black_box(&buf);
        });
    });
    group.finish();
}

// ============================================================================
// Encoder-level benchmarks
// ============================================================================

/// End-to-end `encode_finding` for both FS and Git variants.
///
/// This is the most representative single-event benchmark: it calls
/// `write_json_bytes` (path), `write_u64` (offsets, rule_id), and
/// `write_json_str` (rule_name), composing all primitives into one JSON line.
/// The FS vs. Git delta isolates the cost of the two optional fields.
fn bench_encode_finding(c: &mut Criterion) {
    let mut group = c.benchmark_group("encode_finding");
    group.throughput(Throughput::Elements(1));

    let fs_finding = make_fs_finding();
    group.bench_function("fs_finding", |b| {
        let mut buf = Vec::with_capacity(256);
        b.iter(|| {
            buf.clear();
            encode_finding(black_box(&fs_finding), &mut buf);
            black_box(&buf);
        });
    });

    let git_finding = make_git_finding();
    group.bench_function("git_finding", |b| {
        let mut buf = Vec::with_capacity(256);
        b.iter(|| {
            buf.clear();
            encode_finding(black_box(&git_finding), &mut buf);
            black_box(&buf);
        });
    });

    group.finish();
}

/// End-to-end `encode_commit_meta` with and without identity fields.
///
/// `CommitMeta` events are emitted once per commit (not per finding), so they
/// are less frequent but still latency-sensitive. The identity variant adds
/// four `write_u64` calls; the delta quantifies per-field overhead.
fn bench_encode_commit_meta(c: &mut Criterion) {
    let mut group = c.benchmark_group("encode_commit_meta");
    group.throughput(Throughput::Elements(1));

    let no_id = make_commit_meta_no_identity();
    group.bench_function("no_identity", |b| {
        let mut buf = Vec::with_capacity(256);
        b.iter(|| {
            buf.clear();
            encode_commit_meta(black_box(&no_id), &mut buf);
            black_box(&buf);
        });
    });

    let with_id = make_commit_meta_with_identity();
    group.bench_function("with_identity", |b| {
        let mut buf = Vec::with_capacity(256);
        b.iter(|| {
            buf.clear();
            encode_commit_meta(black_box(&with_id), &mut buf);
            black_box(&buf);
        });
    });

    group.finish();
}

/// Batch-encode 1000 findings through `JsonlEncoder::encode`.
///
/// Simulates a worker's inner loop: encode many events into a shared buffer
/// without I/O. The 50/50 FS/Git mix models a realistic workload. Throughput
/// is reported as elements/sec (1000 findings per iteration) to track
/// amortized per-event cost including buffer growth.
fn bench_encode_batch(c: &mut Criterion) {
    let mut group = c.benchmark_group("encode_batch");
    let encoder = JsonlEncoder::new();

    group.throughput(Throughput::Elements(1000));
    group.bench_function("1000_findings", |b| {
        let mut buf = Vec::with_capacity(256 * 1000);
        let findings: Vec<FindingEvent<'static>> = (0..1000)
            .map(|i| {
                if i % 2 == 0 {
                    make_fs_finding()
                } else {
                    make_git_finding()
                }
            })
            .collect();
        b.iter(|| {
            buf.clear();
            for f in &findings {
                encoder.encode(
                    &ScanEvent::Finding(FindingEvent {
                        source: f.source,
                        object_path: f.object_path,
                        start: f.start,
                        end: f.end,
                        rule_id: f.rule_id,
                        rule_name: f.rule_name,
                        commit_id: f.commit_id,
                        change_kind: f.change_kind,
                    }),
                    &mut buf,
                );
            }
            black_box(&buf);
        });
    });

    group.finish();
}

/// Emit 1000 findings through `JsonlEventSink` into `io::sink()`.
///
/// Unlike `bench_encode_batch`, this exercises the full emit path: thread-local
/// buffer acquisition, encoding, mutex lock, and `write_all`. The `io::sink()`
/// writer discards bytes instantly, so the measured cost is pure serialization
/// + synchronization overhead without I/O latency. Comparing against the batch
///   benchmark isolates the cost of the thread-local + mutex machinery.
fn bench_sink_emit(c: &mut Criterion) {
    let mut group = c.benchmark_group("sink_emit");
    group.throughput(Throughput::Elements(1000));

    group.bench_function("1000_findings_dev_null", |b| {
        let sink = JsonlEventSink::new(io::sink());
        let findings: Vec<FindingEvent<'static>> = (0..1000)
            .map(|i| {
                if i % 2 == 0 {
                    make_fs_finding()
                } else {
                    make_git_finding()
                }
            })
            .collect();
        b.iter(|| {
            for f in &findings {
                sink.emit(ScanEvent::Finding(FindingEvent {
                    source: f.source,
                    object_path: f.object_path,
                    start: f.start,
                    end: f.end,
                    rule_id: f.rule_id,
                    rule_name: f.rule_name,
                    commit_id: f.commit_id,
                    change_kind: f.change_kind,
                }));
            }
        });
    });

    group.finish();
}

/// Emit findings from multiple threads through a shared `JsonlEventSink`.
///
/// Unlike `bench_sink_emit` (single-threaded), this exercises the mutex
/// contention path that production workers encounter. The `io::sink()` writer
/// removes I/O variance, isolating pure formatting + synchronization cost.
fn bench_sink_contention(c: &mut Criterion) {
    let mut group = c.benchmark_group("sink_contention");

    for &threads in &[2, 4, 8] {
        group.throughput(Throughput::Elements(1000));
        group.bench_function(BenchmarkId::new("threads", threads), |b| {
            let sink = std::sync::Arc::new(JsonlEventSink::new(io::sink()));
            let findings: Vec<FindingEvent<'static>> = (0..1000)
                .map(|i| {
                    if i % 2 == 0 {
                        make_fs_finding()
                    } else {
                        make_git_finding()
                    }
                })
                .collect();
            b.iter(|| {
                std::thread::scope(|s| {
                    let per_thread = 1000 / threads;
                    for t in 0..threads {
                        let sink = &sink;
                        let chunk = &findings[t * per_thread..(t + 1) * per_thread];
                        s.spawn(move || {
                            for f in chunk {
                                sink.emit(ScanEvent::Finding(FindingEvent {
                                    source: f.source,
                                    object_path: f.object_path,
                                    start: f.start,
                                    end: f.end,
                                    rule_id: f.rule_id,
                                    rule_name: f.rule_name,
                                    commit_id: f.commit_id,
                                    change_kind: f.change_kind,
                                }));
                            }
                        });
                    }
                });
            });
        });
    }

    group.finish();
}

criterion_group!(
    primitives,
    bench_write_u64,
    bench_write_oid_hex,
    bench_write_json_str,
    bench_write_json_bytes,
    bench_write_f64,
);
criterion_group!(
    encoding,
    bench_encode_finding,
    bench_encode_commit_meta,
    bench_encode_batch,
    bench_sink_emit,
    bench_sink_contention,
);
criterion_main!(primitives, encoding);
